- name: "install node 13.X"
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt -y upgrade
    sudo apt install -y nodejs

- name: Switch Node.js to 13.8.0 with n
  become: true
  shell: |
    sudo npm install --global n
    sudo n 13.8.0

- name: "install pm2 by npm"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: latest

- name: "copy files from CircleCI to server"
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install 