- name: "install node 13.X"
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo npm install -g n
    sudo n 13.8.0

- name: "install pm2 by npm"
  become: true
  npm:
    name: pm2
    global: yes
