

- name: "build package"
  shell: |
    cd /home/ubuntu/backend
    npm run build
- name: "run migrations and save status to https://kvdb.io"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations > migrations.txt
    cat migrations.txt
    export CIRCLE_WORKFLOW_ID="{{ CIRCLE_WORKFLOW_ID }}"
    echo CIRCLE_WORKFLOW_ID=${CIRCLE_WORKFLOW_ID}
    curl https://kvdb.io/NNui4biz8Xuh42cgFYqD5t/migration_status -d "No migrations are pending"
  register: migration_output

- debug:
    msg: "{{ migration_output.stdout_lines }}"

- name: "use pm2 to run the node server"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- run "start:dev"